spring:
#  cache:
#    type: redis
#    cache-names: findOrderById , order #缓存的名字
#    redis:
#      time-to-live: 60000ms  #缓存的有效时间，以便缓存的过期

  redis:
    timeout: 100000ms  # 连接超时时间（毫秒）
    port: 6379  #redis数据库对应的端口号
    host: 127.0.0.1  #对应redis所在的IP地址
    password:
    jedis:
      pool:
        max-wait: 1000ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 500 #连接池的最大数据库连接数
        max-idle: 30 #连接池中的最大空闲连接
        min-idle: 30
    database: 0  # Redis数据库索引,使用第1个数据库，一共默认有16个(0-15)

  thymeleaf:
    cache: false

  datasource:
    url: "jdbc:mysql://localhost:3306/yiban?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      test-on-borrow: true

mybatis:
  type-aliases-package: com.tna.yb_store.entity
  mapper-locations: classpath:com.tna.yb_store.mapper/*Mapper.xml

